import Head from "next/head";
import Feeds from "../components/Feeds";
import Footer from "../components/Footer";
import Model from "../components/Model";
import Header from "../components/Navbar/Header";

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Insta-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Feeds />
    </div>
  );
}
